### ISSUE TITLE
Latest notebook does not compatible with cohere-sagemaker pypi package

### ISSUE THREAD

**Issue by yusharon** [cohere-ai/cohere-aws#21]
Hi Cohere,

When I use the latest notebook in AWS sagemaker, eg, cohere-gpt-medium notebook. I can't get the notebook to execute successfully. This looks like theres a refactor happening recently in the `cohere-sagemaker` Client and latest notebooks, however, this change haven't been released to pypi yet, thus in the notebook it still trying to install the old version of cohere-sagemaker client and cause the notebook throws. Can you solve this?

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-42f7694003fa> in <module>
----> 1 co = Client(region_name=region)
      2 co.create_endpoint(arn=model_package_arn, endpoint_name="cohere-gpt-medium", instance_type="ml.g5.xlarge", n_instances=1)
      3 
      4 # role = get_execution_role()
      5 

TypeError: __init__() missing 1 required positional argument: 'endpoint_name'
```

**Comment by alex-matton** [comment]
Thanks for flagging this, the issue should be fixed now.
