### ISSUE TITLE
Sample notebook - Article Summarization 

### ISSUE THREAD

**Issue by rstrahan** [cohere-ai/cohere-aws#9]
The notebook example for summarization in: **G. Article Summarization using co.generate** does not return a coherent summary of the text in the prompt.. I'm getting random results, such as 
`𝗦𝗨𝗜𝗡𝗧𝗘 𝗢𝗟𝗨𝗥𝗠𝗘𝗡𝗧𝗜𝗖��` 
or
 `𝓐𝓲𝓿𝓵 𝓐𝓲𝓿𝓲𝓲𝓲𝓷𝓪 𝓐𝓲𝓲𝓷`,

See screenshot:

![image](https://user-images.githubusercontent.com/10953374/214956917-03748eae-29c8-44f0-9ec6-263f4fe1193e.png)

Can you provide suggestions on how to improve the summarization example?

**Comment by jpekmez** [comment]
The problem is the trailing white space. We are updating the notebook.
